<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>4. Feedback-ins2</name>
   <tag></tag>
   <elementGuidId>857606f1-fa3b-4a57-bd7e-e5a25481525c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;FeedbackCarInsurance\&quot;: [\n        {\n            \&quot;BatchID\&quot;: \&quot;${batchid}\&quot;,\n            \&quot;NoRek\&quot;: \&quot;${norek}\&quot;,\n            \&quot;NoPin\&quot;: \&quot;${nopin}\&quot;,\n            \&quot;CustName\&quot;: \&quot;${custname}\&quot;,\n            \&quot;Pemohon\&quot;: \&quot;${pemohon}\&quot;,\n            \&quot;Cabang\&quot;: \&quot;${branchid}\&quot;,\n            \&quot;MerkID\&quot;: \&quot;${merk}\&quot;,\n            \&quot;TypeMobil\&quot;: \&quot;${type}\&quot;,\n            \&quot;JenisMobil\&quot;: \&quot;${jenis_mobil}\&quot;,\n            \&quot;Tahun\&quot;: \&quot;${year}\&quot;,\n            \&quot;Warna\&quot;: \&quot;${warna}\&quot;,\n            \&quot;NoRangka\&quot;: \&quot;${no_rangka}\&quot;,\n            \&quot;NoMesin\&quot;: \&quot;${no_mesin}\&quot;,\n            \&quot;NoPolisi\&quot;: \&quot;${nopol}\&quot;,\n            \&quot;Amount2\&quot;: \&quot;${amount2}\&quot;,\n            \&quot;NamaBPKB\&quot;: \&quot;${nama_bpkb}\&quot;,\n            \&quot;PenggunaanKendaraan\&quot;: \&quot;${purpose}\&quot;,\n            \&quot;Kondisi\&quot;: \&quot;${kondisi}\&quot;,\n            \&quot;KondisiPertanggungan\&quot;: \&quot;${ins_type}\&quot;,\n            \&quot;NominalTJH\&quot;: \&quot;${tjh_val}\&quot;,\n            \&quot;InsuredValue\&quot;: \&quot;${ins_value}\&quot;,\n            \&quot;InsuredFrom\&quot;: \&quot;${ins_from}\&quot;,\n            \&quot;InsuredTo\&quot;: \&quot;${ins_to}\&quot;,\n            \&quot;Rate\&quot;: \&quot;${rate}\&quot;,\n            \&quot;GrossPremi\&quot;: \&quot;${gross_premi}\&quot;,\n            \&quot;Discount\&quot;: \&quot;${discount}\&quot;,\n            \&quot;Adm\&quot;: \&quot;${adm}\&quot;,\n            \&quot;NetPremi\&quot;: \&quot;${net_premi}\&quot;,\n            \&quot;Polis\&quot;: \&quot;${polis_no}\&quot;,\n            \&quot;PolisYear\&quot;: \&quot;${polis_year}\&quot;,\n            \&quot;CbgMaskapai\&quot;: \&quot;${cbg_maskapai}\&quot;,\n            \&quot;Text2\&quot;: \&quot;${text2}\&quot;,\n            \&quot;PerluasanJaminan\&quot;: {\n                \&quot;TJH\&quot;: \&quot;${tjh}\&quot;,\n                \&quot;RSCC\&quot;: \&quot;${rscc}\&quot;,\n                \&quot;Banjir\&quot;: \&quot;${banjir}\&quot;,\n                \&quot;Accessories\&quot;: \&quot;${acc}\&quot;\n            }\n        },\n      {\n            \&quot;BatchID\&quot;: \&quot;${batchid2}\&quot;,\n            \&quot;NoRek\&quot;: \&quot;${norek2}\&quot;,\n            \&quot;NoPin\&quot;: \&quot;${nopin2}\&quot;,\n            \&quot;CustName\&quot;: \&quot;${custname2}\&quot;,\n            \&quot;Pemohon\&quot;: \&quot;${pemohon2}\&quot;,\n            \&quot;Cabang\&quot;: \&quot;${branchid2}\&quot;,\n            \&quot;MerkID\&quot;: \&quot;${merk2}\&quot;,\n            \&quot;TypeMobil\&quot;: \&quot;${type2}\&quot;,\n            \&quot;JenisMobil\&quot;: \&quot;${jenis_mobil2}\&quot;,\n            \&quot;Tahun\&quot;: \&quot;${year2}\&quot;,\n            \&quot;Warna\&quot;: \&quot;${warna2}\&quot;,\n            \&quot;NoRangka\&quot;: \&quot;${no_rangka2}\&quot;,\n            \&quot;NoMesin\&quot;: \&quot;${no_mesin2}\&quot;,\n            \&quot;NoPolisi\&quot;: \&quot;${nopol2}\&quot;,\n            \&quot;Amount2\&quot;: \&quot;${amount22}\&quot;,\n            \&quot;NamaBPKB\&quot;: \&quot;${nama_bpkb2}\&quot;,\n            \&quot;PenggunaanKendaraan\&quot;: \&quot;${purpose2}\&quot;,\n            \&quot;Kondisi\&quot;: \&quot;${kondisi2}\&quot;,\n            \&quot;KondisiPertanggungan\&quot;: \&quot;${ins_type2}\&quot;,\n            \&quot;NominalTJH\&quot;: \&quot;${tjh_val2}\&quot;,\n            \&quot;InsuredValue\&quot;: \&quot;${ins_value2}\&quot;,\n            \&quot;InsuredFrom\&quot;: \&quot;${ins_from2}\&quot;,\n            \&quot;InsuredTo\&quot;: \&quot;${ins_to2}\&quot;,\n            \&quot;Rate\&quot;: \&quot;${rate2}\&quot;,\n            \&quot;GrossPremi\&quot;: \&quot;${gross_premi2}\&quot;,\n            \&quot;Discount\&quot;: \&quot;${discount2}\&quot;,\n            \&quot;Adm\&quot;: \&quot;${adm2}\&quot;,\n            \&quot;NetPremi\&quot;: \&quot;${net_premi2}\&quot;,\n            \&quot;Polis\&quot;: \&quot;${polis_no2}\&quot;,\n            \&quot;PolisYear\&quot;: \&quot;${polis_year2}\&quot;,\n            \&quot;CbgMaskapai\&quot;: \&quot;${cbg_maskapai2}\&quot;,\n            \&quot;Text2\&quot;: \&quot;${text22}\&quot;,\n            \&quot;PerluasanJaminan\&quot;: {\n                \&quot;TJH\&quot;: \&quot;${tjh2}\&quot;,\n                \&quot;RSCC\&quot;: \&quot;${rscc2}\&quot;,\n                \&quot;Banjir\&quot;: \&quot;${banjir2}\&quot;,\n                \&quot;Accessories\&quot;: \&quot;${acc2}\&quot;\n            }\n        }\n    ],\n    \&quot;DataPolis\&quot;: {\n        \&quot;JenisDokumen\&quot;: \&quot;CAR01\&quot;,\n        \&quot;file\&quot;: \&quot;base64\&quot;\n    },\n    \&quot;Source\&quot;: \&quot;BCAI\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${s_key}</value>
   </httpHeaderProperties>
   <katalonVersion>8.2.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://api-dev.bcaf.id:8445/feedbackcarinsurance</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.global_token</defaultValue>
      <description></description>
      <id>79b1ded7-459f-41b1-b7e7-73305819dbc5</id>
      <masked>false</masked>
      <name>s_key</name>
   </variables>
   <variables>
      <defaultValue>'A_BCAFNEWTRKSBatch20211215001'</defaultValue>
      <description></description>
      <id>4eb83350-67c2-4fd0-96bc-fab1f60e2421</id>
      <masked>false</masked>
      <name>batchid</name>
   </variables>
   <variables>
      <defaultValue>'1154000993'</defaultValue>
      <description></description>
      <id>40c511b4-4ad1-4ea1-8d88-ef7314edc77d</id>
      <masked>false</masked>
      <name>norek</name>
   </variables>
   <variables>
      <defaultValue>'001'</defaultValue>
      <description></description>
      <id>e77b1dcd-3387-4fab-b2a9-90599cd54b52</id>
      <masked>false</masked>
      <name>nopin</name>
   </variables>
   <variables>
      <defaultValue>'SCRAMBLE'</defaultValue>
      <description></description>
      <id>35628324-0f91-4390-9a6e-235d46754ed1</id>
      <masked>false</masked>
      <name>custname</name>
   </variables>
   <variables>
      <defaultValue>'PT BCAF'</defaultValue>
      <description></description>
      <id>34ecce46-0485-4739-91ba-016dbb3b9d09</id>
      <masked>false</masked>
      <name>pemohon</name>
   </variables>
   <variables>
      <defaultValue>'1154'</defaultValue>
      <description></description>
      <id>8870dd4b-c754-4aa2-8c82-b0eca2a0312f</id>
      <masked>false</masked>
      <name>branchid</name>
   </variables>
   <variables>
      <defaultValue>'360000000.00'</defaultValue>
      <description></description>
      <id>c6e52e54-f2ac-4bb6-85ba-dacf41e392bf</id>
      <masked>false</masked>
      <name>ins_val</name>
   </variables>
   <variables>
      <defaultValue>'TYT'</defaultValue>
      <description></description>
      <id>89fd86a9-e277-424e-b370-e781383cf9af</id>
      <masked>false</masked>
      <name>merk</name>
   </variables>
   <variables>
      <defaultValue>'INNOVA VENTURER 2.0 AT'</defaultValue>
      <description></description>
      <id>49d3ef9b-643c-482b-894c-a93ecd8de123</id>
      <masked>false</masked>
      <name>type</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>95487de0-49f9-424a-8508-99677d756324</id>
      <masked>false</masked>
      <name>jenis_mobil</name>
   </variables>
   <variables>
      <defaultValue>'2017'</defaultValue>
      <description></description>
      <id>04925afa-8d92-4f5b-8ab2-93746fd92a1d</id>
      <masked>false</masked>
      <name>year</name>
   </variables>
   <variables>
      <defaultValue>'PUTIH'</defaultValue>
      <description></description>
      <id>c095511b-18fe-478f-9b7a-bb4d1d6764b7</id>
      <masked>false</masked>
      <name>warna</name>
   </variables>
   <variables>
      <defaultValue>'MHFAW8EM4H0206354'</defaultValue>
      <description></description>
      <id>c6f23a85-7fa8-4f17-9fb6-ce4e2011cc95</id>
      <masked>false</masked>
      <name>no_rangka</name>
   </variables>
   <variables>
      <defaultValue>'1TRA295932'</defaultValue>
      <description></description>
      <id>9ac6d58e-8686-440d-9523-eb1aeba07550</id>
      <masked>false</masked>
      <name>no_mesin</name>
   </variables>
   <variables>
      <defaultValue>'B 2726 BOM'</defaultValue>
      <description></description>
      <id>d5ceb2d4-7b0c-4cc9-a246-789d5b71ba68</id>
      <masked>false</masked>
      <name>nopol</name>
   </variables>
   <variables>
      <defaultValue>'SCRAMBLE'</defaultValue>
      <description></description>
      <id>a1497901-4dd9-4926-a965-1ae74eaf912e</id>
      <masked>false</masked>
      <name>nama_bpkb</name>
   </variables>
   <variables>
      <defaultValue>'10'</defaultValue>
      <description></description>
      <id>04ebd841-0bcc-41d4-ad7c-428b69f3a063</id>
      <masked>false</masked>
      <name>perluasan</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>d77d25d2-48ef-426c-bf26-4b73d5c502a4</id>
      <masked>false</masked>
      <name>acc</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>025a71c2-d371-4ae1-a2d2-485b98c9f695</id>
      <masked>false</masked>
      <name>tjh_header</name>
   </variables>
   <variables>
      <defaultValue>'100'</defaultValue>
      <description></description>
      <id>17a97dc7-445c-4d09-9375-d83bdc422560</id>
      <masked>false</masked>
      <name>tjh_val</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>38d3ab45-b0a7-49b0-abc3-8c00bfcd4cd2</id>
      <masked>false</masked>
      <name>amount2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>1e1133c4-581a-4f1b-b3f4-fa2b2e153e37</id>
      <masked>false</masked>
      <name>text2</name>
   </variables>
   <variables>
      <defaultValue>'Personal'</defaultValue>
      <description></description>
      <id>8c3a32c0-4f92-495f-8ee4-b41f6de40daa</id>
      <masked>false</masked>
      <name>purpose</name>
   </variables>
   <variables>
      <defaultValue>'TLO'</defaultValue>
      <description></description>
      <id>827e0514-8244-437a-b000-f014e6378521</id>
      <masked>false</masked>
      <name>ins_type</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>bb5bb931-9713-4d5e-aaa5-e39db03dd3a7</id>
      <masked>false</masked>
      <name>kondisi</name>
   </variables>
   <variables>
      <defaultValue>'2021-12-14T00:00:00'</defaultValue>
      <description></description>
      <id>15ac80e2-d4cc-4456-ba46-4ce654333bd0</id>
      <masked>false</masked>
      <name>ins_from</name>
   </variables>
   <variables>
      <defaultValue>'2022-12-14T00:00:00'</defaultValue>
      <description></description>
      <id>5b95a2bf-773c-45a1-b12e-dc08987ef5e9</id>
      <masked>false</masked>
      <name>ins_to</name>
   </variables>
   <variables>
      <defaultValue>'BCAFNEWCSI'</defaultValue>
      <description></description>
      <id>6d33292f-9423-4bbb-b8a5-204b57c18335</id>
      <masked>false</masked>
      <name>ins_branch</name>
   </variables>
   <variables>
      <defaultValue>'01-A-1234'</defaultValue>
      <description></description>
      <id>785f87f7-7507-48fe-b9aa-d672bba9038a</id>
      <masked>false</masked>
      <name>polis_no</name>
   </variables>
   <variables>
      <defaultValue>'1.5184'</defaultValue>
      <description></description>
      <id>5eace35a-2560-4300-a2fc-e3bbdaabed29</id>
      <masked>false</masked>
      <name>rate</name>
   </variables>
   <variables>
      <defaultValue>'5466240.00'</defaultValue>
      <description></description>
      <id>558579f3-6156-43cb-82aa-6248c43555d5</id>
      <masked>false</masked>
      <name>gross_premi</name>
   </variables>
   <variables>
      <defaultValue>'0.0000'</defaultValue>
      <description></description>
      <id>9c700a17-1139-487f-ac76-dfc917f1f426</id>
      <masked>false</masked>
      <name>discount</name>
   </variables>
   <variables>
      <defaultValue>'14000.00'</defaultValue>
      <description></description>
      <id>fb28cb04-d139-4aef-9324-3ade532d8a78</id>
      <masked>false</masked>
      <name>adm</name>
   </variables>
   <variables>
      <defaultValue>'5466240.00'</defaultValue>
      <description></description>
      <id>0281c0e9-a720-4ae3-96db-f1a2ae70b9ea</id>
      <masked>false</masked>
      <name>net_premi</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>18f9a27d-31a7-4162-ae69-78300f97d458</id>
      <masked>false</masked>
      <name>polis_year</name>
   </variables>
   <variables>
      <defaultValue>'1234'</defaultValue>
      <description></description>
      <id>45d12705-5053-412e-ba36-4c9585af02b9</id>
      <masked>false</masked>
      <name>cbg_maskapai</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>e8bd32f4-f6a6-4e81-a922-a910188b93e7</id>
      <masked>false</masked>
      <name>tjh</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>f56fa448-4448-477c-b9ea-3763c08ac349</id>
      <masked>false</masked>
      <name>rscc</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>17a675fb-91ed-4674-b52c-776efee028e9</id>
      <masked>false</masked>
      <name>banjir</name>
   </variables>
   <variables>
      <defaultValue>'A_BCAFNEWTRKSBatch20211215001'</defaultValue>
      <description></description>
      <id>4eb83350-67c2-4fd0-96bc-fab1f60e2421</id>
      <masked>false</masked>
      <name>batchid2</name>
   </variables>
   <variables>
      <defaultValue>'1154000993'</defaultValue>
      <description></description>
      <id>40c511b4-4ad1-4ea1-8d88-ef7314edc77d</id>
      <masked>false</masked>
      <name>norek2</name>
   </variables>
   <variables>
      <defaultValue>'001'</defaultValue>
      <description></description>
      <id>e77b1dcd-3387-4fab-b2a9-90599cd54b52</id>
      <masked>false</masked>
      <name>nopin2</name>
   </variables>
   <variables>
      <defaultValue>'SCRAMBLE'</defaultValue>
      <description></description>
      <id>35628324-0f91-4390-9a6e-235d46754ed1</id>
      <masked>false</masked>
      <name>custname2</name>
   </variables>
   <variables>
      <defaultValue>'PT BCAF'</defaultValue>
      <description></description>
      <id>34ecce46-0485-4739-91ba-016dbb3b9d09</id>
      <masked>false</masked>
      <name>pemohon2</name>
   </variables>
   <variables>
      <defaultValue>'1154'</defaultValue>
      <description></description>
      <id>8870dd4b-c754-4aa2-8c82-b0eca2a0312f</id>
      <masked>false</masked>
      <name>branchid2</name>
   </variables>
   <variables>
      <defaultValue>'360000000.00'</defaultValue>
      <description></description>
      <id>c6e52e54-f2ac-4bb6-85ba-dacf41e392bf</id>
      <masked>false</masked>
      <name>ins_val2</name>
   </variables>
   <variables>
      <defaultValue>'TYT'</defaultValue>
      <description></description>
      <id>89fd86a9-e277-424e-b370-e781383cf9af</id>
      <masked>false</masked>
      <name>merk2</name>
   </variables>
   <variables>
      <defaultValue>'INNOVA VENTURER 2.0 AT'</defaultValue>
      <description></description>
      <id>49d3ef9b-643c-482b-894c-a93ecd8de123</id>
      <masked>false</masked>
      <name>type2</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>95487de0-49f9-424a-8508-99677d756324</id>
      <masked>false</masked>
      <name>jenis_mobil2</name>
   </variables>
   <variables>
      <defaultValue>'2017'</defaultValue>
      <description></description>
      <id>04925afa-8d92-4f5b-8ab2-93746fd92a1d</id>
      <masked>false</masked>
      <name>year2</name>
   </variables>
   <variables>
      <defaultValue>'PUTIH'</defaultValue>
      <description></description>
      <id>c095511b-18fe-478f-9b7a-bb4d1d6764b7</id>
      <masked>false</masked>
      <name>warna2</name>
   </variables>
   <variables>
      <defaultValue>'MHFAW8EM4H0206354'</defaultValue>
      <description></description>
      <id>c6f23a85-7fa8-4f17-9fb6-ce4e2011cc95</id>
      <masked>false</masked>
      <name>no_rangka2</name>
   </variables>
   <variables>
      <defaultValue>'1TRA295932'</defaultValue>
      <description></description>
      <id>9ac6d58e-8686-440d-9523-eb1aeba07550</id>
      <masked>false</masked>
      <name>no_mesin2</name>
   </variables>
   <variables>
      <defaultValue>'B 2726 BOM'</defaultValue>
      <description></description>
      <id>d5ceb2d4-7b0c-4cc9-a246-789d5b71ba68</id>
      <masked>false</masked>
      <name>nopol2</name>
   </variables>
   <variables>
      <defaultValue>'SCRAMBLE'</defaultValue>
      <description></description>
      <id>a1497901-4dd9-4926-a965-1ae74eaf912e</id>
      <masked>false</masked>
      <name>nama_bpkb2</name>
   </variables>
   <variables>
      <defaultValue>'10'</defaultValue>
      <description></description>
      <id>04ebd841-0bcc-41d4-ad7c-428b69f3a063</id>
      <masked>false</masked>
      <name>perluasan2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>d77d25d2-48ef-426c-bf26-4b73d5c502a4</id>
      <masked>false</masked>
      <name>acc2</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>025a71c2-d371-4ae1-a2d2-485b98c9f695</id>
      <masked>false</masked>
      <name>tjh_header2</name>
   </variables>
   <variables>
      <defaultValue>'100'</defaultValue>
      <description></description>
      <id>17a97dc7-445c-4d09-9375-d83bdc422560</id>
      <masked>false</masked>
      <name>tjh_val2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>38d3ab45-b0a7-49b0-abc3-8c00bfcd4cd2</id>
      <masked>false</masked>
      <name>amount22</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>1e1133c4-581a-4f1b-b3f4-fa2b2e153e37</id>
      <masked>false</masked>
      <name>text22</name>
   </variables>
   <variables>
      <defaultValue>'Personal'</defaultValue>
      <description></description>
      <id>8c3a32c0-4f92-495f-8ee4-b41f6de40daa</id>
      <masked>false</masked>
      <name>purpose2</name>
   </variables>
   <variables>
      <defaultValue>'TLO'</defaultValue>
      <description></description>
      <id>827e0514-8244-437a-b000-f014e6378521</id>
      <masked>false</masked>
      <name>ins_type2</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>bb5bb931-9713-4d5e-aaa5-e39db03dd3a7</id>
      <masked>false</masked>
      <name>kondisi2</name>
   </variables>
   <variables>
      <defaultValue>'2021-12-14T00:00:00'</defaultValue>
      <description></description>
      <id>15ac80e2-d4cc-4456-ba46-4ce654333bd0</id>
      <masked>false</masked>
      <name>ins_from2</name>
   </variables>
   <variables>
      <defaultValue>'2022-12-14T00:00:00'</defaultValue>
      <description></description>
      <id>5b95a2bf-773c-45a1-b12e-dc08987ef5e9</id>
      <masked>false</masked>
      <name>ins_to2</name>
   </variables>
   <variables>
      <defaultValue>'BCAFNEWCSI'</defaultValue>
      <description></description>
      <id>6d33292f-9423-4bbb-b8a5-204b57c18335</id>
      <masked>false</masked>
      <name>ins_branch2</name>
   </variables>
   <variables>
      <defaultValue>'01-A-1234'</defaultValue>
      <description></description>
      <id>785f87f7-7507-48fe-b9aa-d672bba9038a</id>
      <masked>false</masked>
      <name>polis_no2</name>
   </variables>
   <variables>
      <defaultValue>'1.5184'</defaultValue>
      <description></description>
      <id>5eace35a-2560-4300-a2fc-e3bbdaabed29</id>
      <masked>false</masked>
      <name>rate2</name>
   </variables>
   <variables>
      <defaultValue>'5466240.00'</defaultValue>
      <description></description>
      <id>558579f3-6156-43cb-82aa-6248c43555d5</id>
      <masked>false</masked>
      <name>gross_premi2</name>
   </variables>
   <variables>
      <defaultValue>'0.0000'</defaultValue>
      <description></description>
      <id>9c700a17-1139-487f-ac76-dfc917f1f426</id>
      <masked>false</masked>
      <name>discount2</name>
   </variables>
   <variables>
      <defaultValue>'14000.00'</defaultValue>
      <description></description>
      <id>fb28cb04-d139-4aef-9324-3ade532d8a78</id>
      <masked>false</masked>
      <name>adm2</name>
   </variables>
   <variables>
      <defaultValue>'5466240.00'</defaultValue>
      <description></description>
      <id>0281c0e9-a720-4ae3-96db-f1a2ae70b9ea</id>
      <masked>false</masked>
      <name>net_premi2</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>18f9a27d-31a7-4162-ae69-78300f97d458</id>
      <masked>false</masked>
      <name>polis_year2</name>
   </variables>
   <variables>
      <defaultValue>'1234'</defaultValue>
      <description></description>
      <id>45d12705-5053-412e-ba36-4c9585af02b9</id>
      <masked>false</masked>
      <name>cbg_maskapai2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>e8bd32f4-f6a6-4e81-a922-a910188b93e7</id>
      <masked>false</masked>
      <name>tjh2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>f56fa448-4448-477c-b9ea-3763c08ac349</id>
      <masked>false</masked>
      <name>rscc2</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>1483bf57-4874-4193-b858-1db1ba43b8d6</id>
      <masked>false</masked>
      <name>banjir2</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
